CREATE TABLE Customers (
    CustomerId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    Email NVARCHAR(320) NOT NULL UNIQUE,
    Name NVARCHAR(200) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Orders (
    OrderId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL REFERENCES Customers(CustomerId),
    TotalAmount DECIMAL(18,2) NOT NULL,
    Currency NVARCHAR(10) NOT NULL,
    OrderStatus NVARCHAR(50) NOT NULL DEFAULT 'Received',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE OrderItems (
    OrderItemId BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    OrderId UNIQUEIDENTIFIER NOT NULL REFERENCES Orders(OrderId),
    SKU NVARCHAR(100) NOT NULL,
    ProductName NVARCHAR(400) NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18,4) NOT NULL,
    LineTotal AS (Quantity * UnitPrice) PERSISTED
);

CREATE TABLE IdempotencyRequests (
    RequestId NVARCHAR(100) NOT NULL PRIMARY KEY,
    OrderId UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF TYPE_ID(N'OrderItemType') IS NULL
BEGIN
    CREATE TYPE OrderItemType AS TABLE (
        SKU NVARCHAR(100),
        ProductName NVARCHAR(400),
        Quantity INT,
        UnitPrice DECIMAL(18,4)
    );
END
